OBJS:= arch/$(ARCH)/start.o  $(OBJS) arch/$(ARCH)/alloc.o arch/$(ARCH)/architecture.o \
	arch/$(ARCH)/io.o arch/$(ARCH)/vmm.o arch/$(ARCH)/swap.o arch/$(ARCH)/page_replacement.o arch/$(ARCH)/cow.o \
	arch/$(ARCH)/keyboard.o arch/$(ARCH)/x86.o arch/$(ARCH)/switch.o arch/$(ARCH)/x86int.o arch/$(ARCH)/isr_kbd.o