RUNTIME_OBJS := \
	runtime/cxx.o \
	runtime/itoa.o \
	runtime/memory.o \
	runtime/string.o \
	runtime/buffer.o \
	runtime/buddy.o \
	runtime/slab.o \
	runtime/slob.o \
	runtime/slub.o \
	runtime/unified_alloc.o

OBJS := $(OBJS) $(RUNTIME_OBJS)